# Arrays

In [2]:
import numpy
import numpy as np

def arrays(arr):
    array2 = numpy.array(arr[::-1], dtype = float)
    return array2
    
    # complete this function
    # use numpy.array

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


# Shape and Reshape

In [4]:

import numpy

def arrays(arr):
    A1 = numpy.array(arr, dtype = int).reshape(3,3)
    return A1

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Transpose and Flatten

In [5]:
import numpy
n, m = map(int, input().split())
A1 = numpy.array([input().strip().split() for _ in range(n)], int)
print (A1.transpose())
print (A1.flatten())

2 2
1 3
2 4
[[1 2]
 [3 4]]
[1 3 2 4]


# Concatenate

In [6]:
import numpy

x,y,z = map(int, input().split())
A1 = numpy.array([input().split() for i in range(x+y)], int)

print(A1)

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


# Zeroes and Ones

In [8]:
import numpy

def arrays(arr):
    A1 = numpy.array(arr, dtype = int)
    
    A2 = numpy.zeros(A1, dtype = int)
    A3 = numpy.ones(A1, dtype = int)
    return A2, A3

arr = input().strip().split(' ')
arr2, arr3 = arrays(arr)

print(arr2)
print(arr3)

4 4 4
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


# Eye and Identity

In [9]:
import numpy
numpy.set_printoptions(legacy ='1.13')

x,y = map(int, input().split())
eye = numpy.eye(x,y,0)
print(eye)

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Array Mathematics

In [13]:
import numpy
n,m=map(int,input().split())
A=numpy.array([list(map(int,input().split())) for i in range(n)])
B=numpy.array([list(map(int,input().split())) for i in range(n)])
print(A+B,A-B,A*B,A//B,A%B,A**B,sep='\n')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# Floor,Ceil,Rint

In [14]:
import numpy
numpy.set_printoptions(legacy='1.13')
def arrays(arr):
    A1 = numpy.array(arr, dtype = float)

    f = numpy.floor(A1)
    c = numpy.ceil(A1)
    r = numpy.rint(A1)

    return(f,c,r)    

    
arr = input().strip().split(' ')
floor, ceil, rint = arrays(arr)
print(floor)
print(ceil)
print(rint)

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


# Sum and Prod

In [15]:
import numpy

N, M = map(int, input().split())

A1 = numpy.array([input().split() for i in range(N)], int)

print(numpy.prod(numpy.sum(A1, axis = 0), axis = None))

2 2
1 2
3 4
24


# Min and Max

In [16]:
import numpy
N, M = map(int, input().split())

A1 = numpy.array([input().split() for i in range(N)],dtype = int)
print(numpy.max(numpy.min(A1, axis=1), axis=0))

4 2
3 5
2 9
0 5
3 1
3


# Mean,Var and SD

In [17]:
import numpy

n,m=map(int,input().split())
a=numpy.array([list(map(int,input().split())) for i in range(n)])
print(numpy.mean(a,axis=1))
print(numpy.var(a,axis=0))
numpy.set_printoptions(legacy='1.13')

print(round(numpy.std(a,None),11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


# Dot and Cross

In [18]:
import numpy
N = int(input())
A1 = numpy.array([input().split() for i in range(N)], dtype =int)
A2 = numpy.array([input().split() for i in range(N)], dtype =int)
A3 = numpy.dot(A1,A2)
print(A3)

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


# Inner and Outer

In [19]:
import numpy

A1 = numpy.array(input().split() , int)
A2 = numpy.array(input().split() , int)
print(numpy.inner(A1,A2))
print(numpy.outer(A1,A2))

0 1
2 3
3
[[0 0]
 [2 3]]


# Polynomial

In [20]:
import numpy
x = numpy.array(input().split(), float)
y = float(input())
print(numpy.polyval(x, y))

1.1 2 3
0
3.0


# Linear Algebra

In [21]:
import numpy

numpy.set_printoptions(legacy='1.13')

x = int(input())

A1 = numpy.array([input().split() for i in range(x)], float)
print(numpy.linalg.det(A1))

2
1.1 1.1
1.1 1.1
0.0
